# Generated by Django 3.1 on 2020-08-09 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='users',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Sno',
            new_name='sno',
        ),
    ]
